### ISSUE TITLE
Stripping URL outputs HTML escaped character for the colon ( : )

### ISSUE THREAD

**Issue by aharshac** [wooorm/strip-markdown#13]
If a plain link (without markdown link syntax) is present  in the input, the output of the link has `&#x3A;` in place of ` : `.

![image](https://cloud.githubusercontent.com/assets/11926689/26189431/4d8eb26c-3bc2-11e7-9be0-9d929102b55a.png)

**Comment by wooorm** [comment]
What did you expect would happen?

I think this is correct behaviour: if you pass in emphasis, it’ll become text; if you pass in an auto-link, it’ll become text!

**Comment by aharshac** [comment]
Well, my point is it's not becoming http://www.abc.com/home in the output.

If it's trying to escape the URL, it should become `http&#x3a;&#x2f;&#x2f;www.abc.com&#x2f;home`.

Why is it escaping only the `:` in the output?

**Comment by wooorm** [comment]
It’s not becoming a URL in the text, because as you see in your comment, that would render as something in markdown. Escaping just that colon prevents that (escaping all is just redundant), and that’s essentially what this plugin does!

**Comment by wooorm** [comment]
I feel this is answered, so I’m closing this, but feel free to respond below if you disagree!

**Comment by dtom90** [comment]
This does not make sense to me, as the link is just text in the original markdown. It just happens to get rendered as a clickable link in HTML. What is the markdown formatting that is being "stripped" in this case to give us an escaped `:`?

**Comment by patrickclery** [comment]
> I feel this is answered, so I’m closing this, but feel free to respond below if you disagree!

I'd like to at least see an option to disable this behavior. This creates more steps, and requires me to write string replacement code, which is essentially what I was trying to avoid by using the strip-markdown library.

"https://" is the string value without markup. Adding `&#x3A;` is essentially adding markup when my goal is to strip markup.

EDIT: Also something that occured to me. It's escaping it to HTML entities when I'm not even using this Markdown doc in an HTML context, so that also seems to be a mismatch.

**Comment by kainosnoema** [comment]
This seems to have gotten worse. Now the colon is escaped with `\`. In fact if you have any Markdown character in the text content of the Markdown, they're escaped. I think this is because this plugin is still attempting to output valid Markdown—albeit with complex pieces stripped out—rather than actual plain text.

Examples:

Markdown: `[[Bracketed Link]](https://google.com)`
Stripped: `\[Bracketed Link]`

Markdown: `[https://google.com?param_underscore](https://google.com?param_underscore)`
Stripped: `https\://google.com?param\_underscore`

**Comment by brookback** [comment]
I've got the same problem as @kainosnoema:

**Input**
```
[SOME TEXT]
```

**Output**
```
\\[SOME TEXT]
```

For this code:
```ts
import parse from 'remark-parse';
import strip from 'strip-markdown';
import stringify from 'remark-stringify';

const processor = unified()
  .use(parse)
  .use(strip)
  .use(stringify);
```
