### ISSUE TITLE
Comments cause entire line to be dropped

### ISSUE THREAD

**Issue by strugee** [wooorm/strip-markdown#14]
Seems like HTML comments should just be stripped, but instead putting one on a line causes that entire line to be ignored. I couldn't _really_ tell if this was a bug in the parser or the strip plugin - hope I guessed correctly ;)

Here's a testcase:

```js
'use strict';

const strip = require('strip-markdown'),
      remark = require('remark'),
      processor = remark().use(strip);

const body = '<!-- comment -->foobar'; // It doesn't matter if there's a space before `foobar`

const plaintext = String(processor.processSync(body));

console.log(plaintext); // should be "foobar" but is "" instead

```

Version information:

```
% node -v
v4.8.0

% npm ls remark strip-markdown
issue-format-bot@1.0.0 /Users/alex/Development/HTTPS-Everywhere/utils/issue-format-bot
├── remark@7.0.1
└── strip-markdown@3.0.0
```

Thanks for maintaining remark <3

**Comment by wooorm** [comment]
Thanks for raising this issue!

The problem here arises because an HTML comment at the start of the line “taints” the whole paragraphs as HTML. As an example, I pasted this code:

```markdown
<!--A comment-->, **importance**, and `code`.
```

Below:

, **importance**, and `code`.



As you can see, the importance (bold) and code no longer “work”.

A solution would be to not start the line with HTML:

```markdown
A <!--comment-->, **importance**, and `code`.
```

Yields:

A , **importance**, and `code`.

...and otherwise I wouldn’t really know how to do this in markdown (HTML in markdown is horrible and breaks lots of things). But you could transform the markdown/HTML to HTML first (with [`remark-rehype`](https://github.com/wooorm/remark-rehype) and [`rehype-raw`](https://github.com/wooorm/rehype-raw)) and then strip all tags?

**Comment by strugee** [comment]
@wooorm cool, makes sense. This was mostly just a corner case for processing user input, so I think I'll just throw an error if people write this. Thanks for the suggestion though :-)

Am I correct in thinking that we should leave this open, though, since it seems to be a legitimate bug?

**Comment by wooorm** [comment]
Sorry for the slightly late response!

>  Am I correct in thinking that we should leave this open, though, since it seems to be a legitimate bug?

I dunno, I don’t think this can ever be “fixed”. Other vendors (e.g., markdown-it without `html` enabled) handle this similar...

**Comment by wooorm** [comment]
As this is handled similarly by other markdown parsers (commonmark, markdown-it, gfm), I’d say this is working as it’s supposed to!

**Comment by strugee** [comment]
Ah, sorry, meant to close this myself :)

Cheers!
